import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios'; // Import axios for API requests
import './Adminpanel.css'; // Import the CSS file

const Adminpanel = () => {
  const [mobile, setMobile] = useState(''); // Mobile number entered by the user
  const [otp, setOtp] = useState(''); // OTP generated by the server
  const [otpSent, setOtpSent] = useState(false); // State to track if OTP has been sent
  const [enteredOtp, setEnteredOtp] = useState(''); // State to track entered OTP by user
  const [errorMessage, setErrorMessage] = useState(''); // State to handle error messages
  const navigate = useNavigate(); // Initialize navigate

  // Function to handle OTP sending
  const handleSendOtp = async (event) => {
    event.preventDefault();
    setErrorMessage(''); // Reset the error message before sending OTP

    try {
      // Send request to backend to send OTP (pass the mobile number)
      const response = await axios.post(`${import.meta.env.VITE_API_URL}/check-send-whatsapp-message`, {
        to: mobile // Pass the mobile number to the backend API
      });

      if (response.status === 200) {
        const receivedOtp = response.data.otp; // Get OTP from backend
        console.log("OTP received from backend:", receivedOtp); // Log OTP from backend

        // Ensure OTP is a string (convert to string if not already)
        setOtp(String(receivedOtp)); // Convert OTP to a string explicitly
        setOtpSent(true); // Set OTP sent status to true to show the OTP field
      }
    } catch (error) {
      console.error("Error sending OTP:", error.response ? error.response.data : error.message);
      alert('Failed to send OTP. Please try again later.');
    }
  };

  // Function to handle Admin login with OTP
  const handleAdminLogin = (event) => {
    event.preventDefault();

    // Trim both OTP values before comparison (remove any leading/trailing spaces)
    const cleanedEnteredOtp = enteredOtp.trim();
    const cleanedStoredOtp = otp.trim();

    console.log("Entered OTP:", cleanedEnteredOtp); // Log the OTP entered by user
    console.log("Stored OTP from backend:", cleanedStoredOtp); // Log the OTP stored from backend

    // Check if the entered OTP is correct
    if (cleanedEnteredOtp === cleanedStoredOtp) {
      localStorage.setItem('adminLoggedIn', true); // Set the admin login status
      navigate('/dashboardadmin'); // Redirect to the admin dashboard
    } else {
      // Set the error message if OTP doesn't match
      setErrorMessage('Incorrect OTP, please try again.');
      setEnteredOtp(''); // Reset the entered OTP field
    }
  };

  return (
    <div className="flex h-screen bg-white overflow-hidden">
      <div className="w-full md:w-[55%] flex items-center justify-center mt-5 px-4">
        <div className="w-full max-w-md p-8">
          <div className="flex flex-col items-center mb-2">
            <img src="./image_black.png" alt="login_text" className='mb-2 h-28 w-auto' />
            <img src="./login_subtext.png" alt="login_subtext" className='mb-2 ml-4 h-4 w-auto' />
            <h1 className="text-3d">
              {['A', 'd', 'm', 'i', 'n', ' ',' ', 'L', 'o', 'g', 'i', 'n'].map((letter, index) => (
                <span key={index}>{letter}</span>
              ))}
            </h1>
          </div>
          <form onSubmit={otpSent ? handleAdminLogin : handleSendOtp}>
            <div className="mb-4 mt-10">
              <div className="relative mb-4">
                <input
                  type="text" // Changed to text to accept mobile number (you can also use type="tel" for better mobile number input validation)
                  placeholder="Mobile Number"
                  value={mobile}
                  onChange={(e) => setMobile(e.target.value)}
                  className="w-full p-3 text-black bg-[#F0EDFFCC] rounded-lg"
                  required
                />
              </div>
              {otpSent && (
                <div className="relative mb-3">
                  <input
                    type="text"
                    placeholder="OTP"
                    value={enteredOtp}
                    onChange={(e) => setEnteredOtp(e.target.value)}
                    className="w-full p-3 text-black bg-[#F0EDFFCC] rounded-lg"
                    required
                  />
                </div>
              )}
            </div>

            {errorMessage && (
              <div className="text-red-500 text-sm mb-3">{errorMessage}</div>
            )}

            <div className="flex justify-center mt-6 mb-3">
              <button type="submit" className="w-36 bg-custom-gradient text-white font-poppins font-light py-3 rounded-xl shadow-md text-sm mb-4">
                {otpSent ? 'Submit OTP' : 'Request OTP'}
              </button>
            </div>
          </form>
        </div>
      </div>

      <div className="w-[45%] relative bg-gradient-to-r from-[#9181F4] to-[#5038ED] overflow-hidden flex items-center justify-center">
        <div className="absolute inset-0">
          <img
            src="./login_image.png"
            alt="Login"
            className="w-full h-full object-cover"
          />
        </div>

        <img
          src="./login_page.gif"
          alt="Tab Image"
          className="w-[60%] h-auto object-cover absolute"
          style={{
            top: "50%",
            left: "55%",
            transform: "translate(-50%, -50%)",
            zIndex: 20,
          }}
        />
      </div>
    </div>
  );
};

export default Adminpanel;
